### ISSUE TITLE
script errors

### ISSUE THREAD

**Issue by silverspr** [RobertByrnes/Directory_to_Database#2]
Ubuntu 22.04 PHP 8, script is throwing errors:

php dir2db.php -p /oceanside/RD1/crud5 -r /\.(?:txt)$/
**bash: syntax error near unexpected token `('**

and when I run w/o the -r option:

PHP Fatal error:  Uncaught Error: Class "DataConnection" not found in /home/nova/dir2db-master/classes/FilePathToDatabase.php:10
Stack trace:
#0 /home/nova/dir2db-master/vendor/composer/ClassLoader.php(478): include()
#1 /home/nova/dir2db-master/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#2 /home/nova/dir2db-master/dir2db.php(48): Composer\Autoload\ClassLoader->loadClass()
#3 /home/nova/dir2db-master/dir2db.php(44): run()
#4 {main}
  thrown in /home/nova/dir2db-master/classes/FilePathToDatabase.php on line 10

**Comment by RobertByrnes** [comment]
@silverspr The package has been updated - I have pushed v1.0.2 to packagist. Please reinstall using ```composer req robertbyrnes/dir2db``` the post install hook should copy the .ini file for the database over to /private/local.ini for you and then you will need to edit it to add your database details. Please note the dir2db.php file now exists in the /src directory rather than in the package root... 

The issue you describe is now fixed by adding the missing dependencies, thank you for raising it 👍

**Comment by silverspr** [comment]
...cleaned email reply Continuing on… the problem is more likely me!!  
I’m calling “php dir2db” from inside the src folder, throws an error.  I don’t see either the vendor folder or autoload.php file in the installed folder:
$:~/dir2db-master/src$ php dir2db.php throw the following error:

PHP Warning:  require_once(/home/nova/dir2db-master/src/../vendor/autoload.php): Failed to open stream: No such file or directory in /home/nova/dir2db-master/src/dir2db.php on line 5PHP Fatal error:  Uncaught Error: Failed opening required '/home/nova/dir2db-master/src/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/nova/dir2db-master/src/dir2db.php:5
Stack trace:#0 {main}  thrown in /home/nova/dir2db-master/src/dir2db.php on line 5 

thanks again

**Comment by RobertByrnes** [comment]
Hi, no worries. It may be that you need to run 'composer install' in the package root first. Then run 'composer dumpautoload -o'. Let me know if you're still erroring after that. Please also remember to give the full path or correct relative path when passing -p

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RobertByrnes** [comment]
Hi, I think I have managed to simplify the install! I have also updated the README.md to that effect. Just install via ``` git clone https://github.com/RobertByrnes/dir2db.git ``` then cd into package root directory and run ``` composer post-package-install ```

**Comment by silverspr** [comment]
g'day, 
Running the composer install from the root of the dir2db directory throws this error:
~/dir2db-master$ composer require robertbyrnes/dir2db
Root package 'robertbyrnes/dir2db' cannot require itself in its composer.json

The previous install run from the home directory, completed w/o issue.  Note, I still had to create the local.ini file (I understood this process was no longer required).

Running composer dumpautoload -o from root of dir2db
Generating optimized autoload files
Class dir2db\deployment\Deploy located in ./deploy.php does not comply with psr-4 autoloading standard. Skipping.
Generated optimized autoload files containing 5 classes  <<< yayyy

nova@ubuntu:~/dir2db-master/src$ php dir2db.php -p /oceanside/RD1/crud5/ 
**PHP Fatal error:  $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax in /home/nova/dir2db-master/src/DataConnection.php on line** 37

p.s. I have a local.ini file in both the dir2db root and the src folder...thinking the above error was because I had't placed the file correctly.

thanks

**Comment by RobertByrnes** [comment]
Hi @silverspr 

Okay so pull the master branch again and run the same ``` php dir2db.php -p /oceanside/RD1/crud5/ ``` - the DataConnection.php is working cheers, will look at the ``` Class dir2db\deployment\Deploy located in ./deploy.php does not comply with psr-4 autoloading standard. ``` bit later. :)

**Comment by RobertByrnes** [comment]
Hi @silverspr, ok deployment of .ini now working aswell, let me if any more trouble but please do also update if all okay. Working on windows and also on ubuntu ...

**Comment by silverspr** [comment]
Getting there :) 
The script runs without regex option and inserts into the database/table BUT when I add the regex:
**php dir2db.php -p /oceanside/RD1/crud5/ -r /.(?:pdf)$/ -e AutoIndex
bash: syntax error near unexpected token `('**

(I tried with and without quotes just to be on the safe side, neither worked)

the option to have multiple document types?  pdf | txt | rtf | docx | ods would be a bonus...

**Comment by RobertByrnes** [comment]
ok - try now with your regex :) ... but do use quotes e.g. ```-r "/.(?:pdf)$/"``` and you can also use multiple types just with regex e.g.  ```-r "/.(?:pdf|txt|rtf|docx|ods)$/"```

**Comment by silverspr** [comment]
I'm starting to feel bad... regex is ignored and exceptions are ignored.  Do you think I still have an install problem?  Once this is working does the script look for all folders or is it one folder at a time:? I can't tell with it falling back to default parameters.
thanks

php dir2db.php -p /oceanside/RD1/crud5/ -r "/.(?:pdf)$/"  -e AutoIndex
... snippet..
[+] Searching directories for .php files

[+] 41 Files found.

[+] Inserting files into database.

[+] File inserted: /oceanside/RD1/crud5/search.php
[+] Row count: 1
[+] File inserted: /oceanside/RD1/crud5/zsearch.php
[+] Row count: 2
[+] File inserted: /oceanside/RD1/crud5/AutoIndex/AutoIndex.conf.php
[+] Row count: 3
[+] File inserted: /oceanside/RD1/crud5/AutoIndex/index.php
... snippet,,

then I tried switching to a different folder with no php files and would avoid need for exceptions:

php dir2db.php -p /oceanside/RD1/crud5/Tarts/ -r "/.(?:pdf)$/" -e AutoIndex

[+] Searching directories for .php files

[+] 1 Files found.

[+] Inserting files into database.

PHP Warning:  file_get_contents(No files discovered within search parameters.): Failed to open stream: No such file or directory in /home/nova/dir2db-master/src/FilePathToDatabase.php on line 66
[+] File inserted: No files discovered within search parameters.
[+] Row count: 1
PHP Fatal error:  Uncaught TypeError: feof(): Argument #1 ($stream) must be of type resource, bool given in /home/nova/dir2db-master/src/FilePathToDatabase.php:100
Stack trace:
#0 /home/nova/dir2db-master/src/FilePathToDatabase.php(100): feof()
#1 /home/nova/dir2db-master/src/FilePathToDatabase.php(80): dir2db\FilePathToDatabase->getClassNameFromFile()
#2 /home/nova/dir2db-master/src/FilePathToDatabase.php(43): dir2db\FilePathToDatabase->insertFilesToDatabase()
#3 /home/nova/dir2db-master/src/dir2db.php(50): dir2db\FilePathToDatabase->__construct()
#4 /home/nova/dir2db-master/src/dir2db.php(46): dir2db\run()
#5 {main}
  thrown in /home/nova/dir2db-master/src/FilePathToDatabase.php on line 100

this just might be because the search failed for php files.

**Comment by RobertByrnes** [comment]
Hi @silverspr please give it another pop, it's had a bit of a face lift and passing unit tests for both the regex and  directory excludes as well some hardening around the file_get_contents.

probably a good idea to make sure you get the latest version, you need to use version 1.1.1 ...

good luck :)

**Comment by silverspr** [comment]
hi @RobertByrnes , well we are getting there.  good news is we are past installation/regex errors and onto uploading into db. Regex is recognized as is folder exclusions. 

However I have a lot of insert failures.  3 out of 5 txt files failed to insert, NO pdf files inserted out of 831.  I'm not getting any errors in mysql log. I don't see any pattern in the failures i.e. spaces in folder name or document title might be a factor but doesn't appear to be.  The only thing that comes to mind is the 'complete file' field...parsing errors?  Thanks for all your work on this, much appreciated.  FYI a hyperlink to the file vs a the complete file would sort of accomplish the same thing.  just a thought.

**Comment by RobertByrnes** [comment]
@silverspr Hi again, I have now added binary file types to the mix .... ! You will be able to get your .pdf files into the database but you will need to rebuild your database table as the .sql file has changed to accommodate this. Binary file contents are stored as a `LONGBLOB` column named `binary_file_content`. Other file extensions are stored now as `LONGTEXT` in the `file_content` column.

This is now moving a bit beyond the original scope of this repo as I only wrote it to get php into a database to use Reflection on. I am happy to see it extended support other file types.

As long as you can achieve the .pdf file insertions I would consider this a success and ask that you please close this issue. Also, I'd would be very grateful if you would star the repo. Please also feel free to submit PR's to extend the functionality of this package.

Happy coding :)

**Comment by silverspr** [comment]
@RobertByrnes  Holy smoke ... this is awesome, loaded 722 pdf/txt in under a minute.  I have to figure out how to use the blob data type, I was able to save it to file and actually open it.  Yes I will indeed close the issue, and you could have indicated this work was out of scope, but you have made the script AWESOME!  

Just one last comment, out of 4 txt files, only 2 loaded.  attached the log file for the error...I can't see anything different with the text files that loaded vs not:

2023-04-08T14:28:37-07:00 [ERROR] : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\x92s the...' for column `test_enviro`.`dir2db_content`.`file_content` at row 1
#0 /home/nova/dir2db-master/src/DataConnection.php(127): PDOStatement->execute()
#1 /home/nova/dir2db-master/src/DataConnection.php(149): dir2db\DataConnection->preparedInsert()
#2 /home/nova/dir2db-master/src/FilePathToDatabase.php(77): dir2db\DataConnection->preparedInsertGetCount()
#3 /home/nova/dir2db-master/src/FilePathToDatabase.php(33): dir2db\FilePathToDatabase->insertFilesToDatabase()
#4 /home/nova/dir2db-master/src/dir2db.php(48): dir2db\FilePathToDatabase->__construct()
#5 /home/nova/dir2db-master/src/dir2db.php(45): dir2db\run()
#6 {main}
